channels:
  - conda-forge
dependencies:
  - cuda
  - cuda-version=12.8
  - ecmwf-opendata=0.3.20
  - earthkit-data=0.15.0
  - earthkit-utils=0.0.1
  - flash-attn=2.7.2
# h3 is anemoi_graphs dependency. We only need the python-binding and so h3-py. pip has problem with cmake version when trying to install h3
  - h3-py >=3.7.7,<4
  - huggingface_hub
  - matplotlib
  - numpy
  - pip
  - python

    # Only install with pip as a fallback
  - pip:
    - anemoi_datasets==0.5.23
    - anemoi_graphs==0.6.0
    - anemoi_inference==0.6.0
    - anemoi_models==0.6.0
    - anemoi_transform==0.1.11
    - anemoi_utils==0.4.28
    - earthkit_meteo==0.4.1
    - earthkit_regrid==0.4.0

# anemoi deps - prefer using conda to pip
  - aniso8601
  - anytree
  - array-api-compat
  - attrs
  - cartopy
  - cfgrib
  - cfunits
  - dask
    # - eccodes >2.38 # not recognised by pip packages
  - einops
  - entrypoints
  - findlibs
  - gitdb
  - gitpython
  - hydra-core
  - joblib
  - jsonschema
  - jsonschema-specifications
  - lru-dict
  - markdown
  - netcdf4
  - packaging
    # - pdbufr # not recognised by pip packages
  - pydantic
  - pytorch
  - pytorch_geometric >=2.3,<2.5
  - pyyaml
  - referencing
  - rpds-py
  - scikit-learn
  - semantic_version
  - smmap <6
  - termcolor
  - threadpoolctl
  - tqdm
  - wcwidth
  - xarray
  - ecmwf-api-client
